### ISSUE TITLE
How to define  PAS as 1bp site?

### ISSUE THREAD

**Issue by rpghjs** [YangLab/SCAPTURE#1]
Thanks for you developing this method.
We are now applying this method on our data and  generated a set of PAS.
We want to compare it with known pas descrabed as 1bp sites.
Is it  appropriate  to convert the PAS site generated by SCAPTURE which are described as regions to 1bp sites?
We found that the 7th and 8th column in the outputs of intronic and 3primeExtended defined 1bp sites, but in the output of exonic these two column defined regions.
How can we defined a PAS site in exonic output as 1bp sites?
Thanks ahead for your help.

**Comment by liguowei-CAS** [comment]
I am not for sure what do you mean "1 bp sites". Does that mean the exact sites of PASs? Most sequencing-predicted PASs might not be able to reach single nucleotide resolution, but reported to clusters. Usually, you can try to define the last nucleotide position of a cluster as "1 bo sites" for those methods. 
For SCAPTURE, we will output the region (default 400 bp) of reads from 3' end, near to poly(A) site, of a transcript. The region was recorded in widely-used [BED format](https://genome.ucsc.edu/FAQ/FAQformat.html#format1.7). And the 7th and 8th column should NOT be treated as 1 bp site, please read BED format document carefully. Otherwise, the last nucleotide position of SCAPTURE output BED file could be extracted by command:

 `awk 'BEGIN{FS="\t";OFS="\t"}{if ($6=="+") print $1,$3-1,$3,$4,$5,$6; else if ($6=="-") print $1,$2,$2+1,$4,$5,$6; else print "unknown strand"}' SCAPTURE.bed`

**Comment by rpghjs** [comment]
Thanks for your reply!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月31日(星期二) 下午2:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YangLab/SCAPTURE] How to define  PAS as 1bp site? (#1)





 
我不确定“1 bp 站点”是什么意思。这是否意味着 PAS 的确切位置？大多数测序预测的 PAS 可能无法达到单核苷酸分辨率，但会报告给集群。通常，对于这些方法，您可以尝试将簇的最后一个核苷酸位置定义为“1 bo 位点”。
 对于 SCAPTURE，我们将输出转录本 3' 末端靠近 poly(A) 位点的读数区域（默认 400 bp）。该地区以广泛使用的BED 格式记录。并且第 7 和第 8 列不应被视为 1 bp 站点，请仔细阅读 BED 格式文档。否则，可以通过命令提取 SCAPTURE 输出 BED 文件的最后一个核苷酸位置：
 
awk 'BEGIN{FS="\t";OFS="\t"}{if ($6=="+") print $1,$3-1,$3,$4,$5,$6; else if ($6=="-") print $1,$2,$2+1,$4,$5,$6; else print "unknown strand"}' SCAPTURE.bed
 
—
您收到此消息是因为您创作了该线程。
直接回复此邮件，在 GitHub 上查看，或取消订阅。
使用 GitHub Mobile for iOS或Android随时随地分类通知。
